# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/uub_proto_wrapper.xdc

# XDC: imports/constraints/vivado_uub.xdc

# XDC: imports/constraints/Timing_contraints_uub.xdc

# Block Designs: bd/uub_proto2/uub_proto2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2 || ORIG_REF_NAME==uub_proto2}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_uartlite_0_0/uub_proto2_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_uartlite_0_0 || ORIG_REF_NAME==uub_proto2_axi_uartlite_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_clock_1pps_0_0/uub_proto2_clock_1pps_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_clock_1pps_0_0 || ORIG_REF_NAME==uub_proto2_clock_1pps_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_0_0/uub_proto2_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_0_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_time_tagging_0_0/uub_proto2_time_tagging_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_time_tagging_0_0 || ORIG_REF_NAME==uub_proto2_time_tagging_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_0/uub_proto2_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_0_0 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_1_0/uub_proto2_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_1_0 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_2_0/uub_proto2_blk_mem_gen_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_2_0 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_2_0}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_3_0/uub_proto2_blk_mem_gen_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_3_0 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_3_0}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_4_0/uub_proto2_blk_mem_gen_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_4_0 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_4_0}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconstant_0_0/uub_proto2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconstant_0_0 || ORIG_REF_NAME==uub_proto2_xlconstant_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconstant_1_0/uub_proto2_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconstant_1_0 || ORIG_REF_NAME==uub_proto2_xlconstant_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_6_0/uub_proto2_blk_mem_gen_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_6_0 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_6_0}]

# IP: bd/uub_proto2/ip/uub_proto2_sde_trigger_0_0/uub_proto2_sde_trigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_sde_trigger_0_0 || ORIG_REF_NAME==uub_proto2_sde_trigger_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_5_0/uub_proto2_util_ds_buf_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_5_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_5_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_7_0/uub_proto2_util_ds_buf_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_7_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_7_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_11_0/uub_proto2_util_ds_buf_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_11_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_11_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_8_0/uub_proto2_util_ds_buf_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_8_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_8_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_6_0/uub_proto2_util_ds_buf_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_6_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_6_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_10_0/uub_proto2_util_ds_buf_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_10_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_10_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_2_0/uub_proto2_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_2_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_2_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_4_0/uub_proto2_util_ds_buf_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_4_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_4_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_1_0/uub_proto2_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_1_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_ds_buf_3_0/uub_proto2_util_ds_buf_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_ds_buf_3_0 || ORIG_REF_NAME==uub_proto2_util_ds_buf_3_0}]

# IP: bd/uub_proto2/ip/uub_proto2_ddr_synchronizer_24bit_0_0/uub_proto2_ddr_synchronizer_24bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_ddr_synchronizer_24bit_0_0 || ORIG_REF_NAME==uub_proto2_ddr_synchronizer_24bit_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_ddr_synchronizer_24bit_1_0/uub_proto2_ddr_synchronizer_24bit_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_ddr_synchronizer_24bit_1_0 || ORIG_REF_NAME==uub_proto2_ddr_synchronizer_24bit_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_ddr_synchronizer_24bit_2_0/uub_proto2_ddr_synchronizer_24bit_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_ddr_synchronizer_24bit_2_0 || ORIG_REF_NAME==uub_proto2_ddr_synchronizer_24bit_2_0}]

# IP: bd/uub_proto2/ip/uub_proto2_ddr_synchronizer_24bit_3_0/uub_proto2_ddr_synchronizer_24bit_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_ddr_synchronizer_24bit_3_0 || ORIG_REF_NAME==uub_proto2_ddr_synchronizer_24bit_3_0}]

# IP: bd/uub_proto2/ip/uub_proto2_ddr_synchronizer_24bit_4_0/uub_proto2_ddr_synchronizer_24bit_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_ddr_synchronizer_24bit_4_0 || ORIG_REF_NAME==uub_proto2_ddr_synchronizer_24bit_4_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_interconnect_1_0/uub_proto2_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_interconnect_1_0 || ORIG_REF_NAME==uub_proto2_axi_interconnect_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_proc_sys_reset_0_0/uub_proto2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_proc_sys_reset_0_0 || ORIG_REF_NAME==uub_proto2_proc_sys_reset_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_processing_system7_0_0/uub_proto2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_processing_system7_0_0 || ORIG_REF_NAME==uub_proto2_processing_system7_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconcat_0_0/uub_proto2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconcat_0_0 || ORIG_REF_NAME==uub_proto2_xlconcat_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_cdma_0_0/uub_proto2_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_cdma_0_0 || ORIG_REF_NAME==uub_proto2_axi_cdma_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_xbar_0/uub_proto2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xbar_0 || ORIG_REF_NAME==uub_proto2_xbar_0}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_3_1/uub_proto2_blk_mem_gen_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_3_1 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_3_1}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_0/uub_proto2_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_1_0/uub_proto2_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_1_0 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_2_0/uub_proto2_axi_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_2_0 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_2_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_3_0/uub_proto2_axi_bram_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_3_0 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_3_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_4_0/uub_proto2_axi_bram_ctrl_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_4_0 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_4_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_5_0/uub_proto2_axi_bram_ctrl_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_5_0 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_5_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_6_0/uub_proto2_axi_bram_ctrl_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_6_0 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_6_0}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconstant_0_1/uub_proto2_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconstant_0_1 || ORIG_REF_NAME==uub_proto2_xlconstant_0_1}]

# IP: bd/uub_proto2/ip/uub_proto2_fir_compiler_0_1/uub_proto2_fir_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_fir_compiler_0_1 || ORIG_REF_NAME==uub_proto2_fir_compiler_0_1}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconcat_0_2/uub_proto2_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconcat_0_2 || ORIG_REF_NAME==uub_proto2_xlconcat_0_2}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconstant_0_4/uub_proto2_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconstant_0_4 || ORIG_REF_NAME==uub_proto2_xlconstant_0_4}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconstant_1_1/uub_proto2_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconstant_1_1 || ORIG_REF_NAME==uub_proto2_xlconstant_1_1}]

# IP: bd/uub_proto2/ip/uub_proto2_xlslice_1_2/uub_proto2_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlslice_1_2 || ORIG_REF_NAME==uub_proto2_xlslice_1_2}]

# IP: bd/uub_proto2/ip/uub_proto2_xlslice_2_0/uub_proto2_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlslice_2_0 || ORIG_REF_NAME==uub_proto2_xlslice_2_0}]

# IP: bd/uub_proto2/ip/uub_proto2_fir_compiler_0_2/uub_proto2_fir_compiler_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_fir_compiler_0_2 || ORIG_REF_NAME==uub_proto2_fir_compiler_0_2}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconcat_0_3/uub_proto2_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconcat_0_3 || ORIG_REF_NAME==uub_proto2_xlconcat_0_3}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconstant_1_2/uub_proto2_xlconstant_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconstant_1_2 || ORIG_REF_NAME==uub_proto2_xlconstant_1_2}]

# IP: bd/uub_proto2/ip/uub_proto2_xlslice_2_1/uub_proto2_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlslice_2_1 || ORIG_REF_NAME==uub_proto2_xlslice_2_1}]

# IP: bd/uub_proto2/ip/uub_proto2_xlslice_3_0/uub_proto2_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlslice_3_0 || ORIG_REF_NAME==uub_proto2_xlslice_3_0}]

# IP: bd/uub_proto2/ip/uub_proto2_fir_compiler_0_3/uub_proto2_fir_compiler_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_fir_compiler_0_3 || ORIG_REF_NAME==uub_proto2_fir_compiler_0_3}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconcat_0_4/uub_proto2_xlconcat_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconcat_0_4 || ORIG_REF_NAME==uub_proto2_xlconcat_0_4}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconstant_1_3/uub_proto2_xlconstant_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconstant_1_3 || ORIG_REF_NAME==uub_proto2_xlconstant_1_3}]

# IP: bd/uub_proto2/ip/uub_proto2_xlslice_2_2/uub_proto2_xlslice_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlslice_2_2 || ORIG_REF_NAME==uub_proto2_xlslice_2_2}]

# IP: bd/uub_proto2/ip/uub_proto2_xlslice_3_1/uub_proto2_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlslice_3_1 || ORIG_REF_NAME==uub_proto2_xlslice_3_1}]

# IP: bd/uub_proto2/ip/uub_proto2_xlconstant_0_2/uub_proto2_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xlconstant_0_2 || ORIG_REF_NAME==uub_proto2_xlconstant_0_2}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_interconnect_0_1/uub_proto2_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_interconnect_0_1 || ORIG_REF_NAME==uub_proto2_axi_interconnect_0_1}]

# IP: bd/uub_proto2/ip/uub_proto2_xbar_2/uub_proto2_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_xbar_2 || ORIG_REF_NAME==uub_proto2_xbar_2}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_crossbar_0_1/uub_proto2_axi_crossbar_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_crossbar_0_1 || ORIG_REF_NAME==uub_proto2_axi_crossbar_0_1}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_crossbar_0_0/uub_proto2_axi_crossbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_crossbar_0_0 || ORIG_REF_NAME==uub_proto2_axi_crossbar_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_crossbar_1_0/uub_proto2_axi_crossbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_crossbar_1_0 || ORIG_REF_NAME==uub_proto2_axi_crossbar_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_crossbar_2_0/uub_proto2_axi_crossbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_crossbar_2_0 || ORIG_REF_NAME==uub_proto2_axi_crossbar_2_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_crossbar_3_0/uub_proto2_axi_crossbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_crossbar_3_0 || ORIG_REF_NAME==uub_proto2_axi_crossbar_3_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_crossbar_0_2/uub_proto2_axi_crossbar_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_crossbar_0_2 || ORIG_REF_NAME==uub_proto2_axi_crossbar_0_2}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_crossbar_1_1/uub_proto2_axi_crossbar_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_crossbar_1_1 || ORIG_REF_NAME==uub_proto2_axi_crossbar_1_1}]

# IP: bd/uub_proto2/ip/uub_proto2_interface_uub_dfn3_0_1/uub_proto2_interface_uub_dfn3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_interface_uub_dfn3_0_1 || ORIG_REF_NAME==uub_proto2_interface_uub_dfn3_0_1}]

# IP: bd/uub_proto2/ip/uub_proto2_WP1_ADC_Control_0_0/uub_proto2_WP1_ADC_Control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_WP1_ADC_Control_0_0 || ORIG_REF_NAME==uub_proto2_WP1_ADC_Control_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_1/uub_proto2_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_0_1 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_0_1}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_2/uub_proto2_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_0_2 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_0_2}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_3/uub_proto2_blk_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_0_3 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_0_3}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_4/uub_proto2_blk_mem_gen_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_0_4 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_0_4}]

# IP: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_5/uub_proto2_blk_mem_gen_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_blk_mem_gen_0_5 || ORIG_REF_NAME==uub_proto2_blk_mem_gen_0_5}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_1/uub_proto2_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_0_1 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_0_1}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_2/uub_proto2_axi_bram_ctrl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_0_2 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_0_2}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_3/uub_proto2_axi_bram_ctrl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_0_3 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_0_3}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_4/uub_proto2_axi_bram_ctrl_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_0_4 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_0_4}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_5/uub_proto2_axi_bram_ctrl_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_bram_ctrl_0_5 || ORIG_REF_NAME==uub_proto2_axi_bram_ctrl_0_5}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_gpio_0_0/uub_proto2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_gpio_0_0 || ORIG_REF_NAME==uub_proto2_axi_gpio_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_axi_gpio_1_0/uub_proto2_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_axi_gpio_1_0 || ORIG_REF_NAME==uub_proto2_axi_gpio_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_WP7_LED_Control_0_0/uub_proto2_WP7_LED_Control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_WP7_LED_Control_0_0 || ORIG_REF_NAME==uub_proto2_WP7_LED_Control_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_util_vector_logic_0_0/uub_proto2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_util_vector_logic_0_0 || ORIG_REF_NAME==uub_proto2_util_vector_logic_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_tier2_xbar_0_0/uub_proto2_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_tier2_xbar_0_0 || ORIG_REF_NAME==uub_proto2_tier2_xbar_0_0}]

# IP: bd/uub_proto2/ip/uub_proto2_tier2_xbar_1_0/uub_proto2_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_tier2_xbar_1_0 || ORIG_REF_NAME==uub_proto2_tier2_xbar_1_0}]

# IP: bd/uub_proto2/ip/uub_proto2_tier2_xbar_2_0/uub_proto2_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_tier2_xbar_2_0 || ORIG_REF_NAME==uub_proto2_tier2_xbar_2_0}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_0/uub_proto2_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_0 || ORIG_REF_NAME==uub_proto2_auto_ds_0}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_1/uub_proto2_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_1 || ORIG_REF_NAME==uub_proto2_auto_ds_1}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_2/uub_proto2_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_2 || ORIG_REF_NAME==uub_proto2_auto_ds_2}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_3/uub_proto2_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_3 || ORIG_REF_NAME==uub_proto2_auto_ds_3}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_4/uub_proto2_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_4 || ORIG_REF_NAME==uub_proto2_auto_ds_4}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_5/uub_proto2_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_5 || ORIG_REF_NAME==uub_proto2_auto_ds_5}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_6/uub_proto2_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_6 || ORIG_REF_NAME==uub_proto2_auto_ds_6}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_0/uub_proto2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_0 || ORIG_REF_NAME==uub_proto2_auto_pc_0}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_us_0/uub_proto2_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_us_0 || ORIG_REF_NAME==uub_proto2_auto_us_0}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_us_1/uub_proto2_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_us_1 || ORIG_REF_NAME==uub_proto2_auto_us_1}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_7/uub_proto2_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_7 || ORIG_REF_NAME==uub_proto2_auto_ds_7}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_1/uub_proto2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_1 || ORIG_REF_NAME==uub_proto2_auto_pc_1}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_8/uub_proto2_auto_ds_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_8 || ORIG_REF_NAME==uub_proto2_auto_ds_8}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_2/uub_proto2_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_2 || ORIG_REF_NAME==uub_proto2_auto_pc_2}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_9/uub_proto2_auto_ds_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_9 || ORIG_REF_NAME==uub_proto2_auto_ds_9}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_3/uub_proto2_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_3 || ORIG_REF_NAME==uub_proto2_auto_pc_3}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_10/uub_proto2_auto_ds_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_10 || ORIG_REF_NAME==uub_proto2_auto_ds_10}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_4/uub_proto2_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_4 || ORIG_REF_NAME==uub_proto2_auto_pc_4}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_11/uub_proto2_auto_ds_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_11 || ORIG_REF_NAME==uub_proto2_auto_ds_11}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_5/uub_proto2_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_5 || ORIG_REF_NAME==uub_proto2_auto_pc_5}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_12/uub_proto2_auto_ds_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_12 || ORIG_REF_NAME==uub_proto2_auto_ds_12}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_6/uub_proto2_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_6 || ORIG_REF_NAME==uub_proto2_auto_pc_6}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_13/uub_proto2_auto_ds_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_13 || ORIG_REF_NAME==uub_proto2_auto_ds_13}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_14/uub_proto2_auto_ds_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_14 || ORIG_REF_NAME==uub_proto2_auto_ds_14}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_15/uub_proto2_auto_ds_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_15 || ORIG_REF_NAME==uub_proto2_auto_ds_15}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_16/uub_proto2_auto_ds_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_16 || ORIG_REF_NAME==uub_proto2_auto_ds_16}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_17/uub_proto2_auto_ds_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_17 || ORIG_REF_NAME==uub_proto2_auto_ds_17}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_18/uub_proto2_auto_ds_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_18 || ORIG_REF_NAME==uub_proto2_auto_ds_18}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_19/uub_proto2_auto_ds_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_19 || ORIG_REF_NAME==uub_proto2_auto_ds_19}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_20/uub_proto2_auto_ds_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_20 || ORIG_REF_NAME==uub_proto2_auto_ds_20}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_21/uub_proto2_auto_ds_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_21 || ORIG_REF_NAME==uub_proto2_auto_ds_21}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_22/uub_proto2_auto_ds_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_22 || ORIG_REF_NAME==uub_proto2_auto_ds_22}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_23/uub_proto2_auto_ds_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_23 || ORIG_REF_NAME==uub_proto2_auto_ds_23}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_24/uub_proto2_auto_ds_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_24 || ORIG_REF_NAME==uub_proto2_auto_ds_24}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_25/uub_proto2_auto_ds_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_25 || ORIG_REF_NAME==uub_proto2_auto_ds_25}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_7/uub_proto2_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_7 || ORIG_REF_NAME==uub_proto2_auto_pc_7}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_ds_26/uub_proto2_auto_ds_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_26 || ORIG_REF_NAME==uub_proto2_auto_ds_26}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_8/uub_proto2_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_8 || ORIG_REF_NAME==uub_proto2_auto_pc_8}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_pc_9/uub_proto2_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_pc_9 || ORIG_REF_NAME==uub_proto2_auto_pc_9}]

# IP: bd/uub_proto2/ip/uub_proto2_auto_us_2/uub_proto2_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_auto_us_2 || ORIG_REF_NAME==uub_proto2_auto_us_2}]

# XDC: bd/uub_proto2/ip/uub_proto2_axi_uartlite_0_0/uub_proto2_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_axi_uartlite_0_0 || ORIG_REF_NAME==uub_proto2_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uub_proto2/ip/uub_proto2_axi_uartlite_0_0/uub_proto2_axi_uartlite_0_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_uartlite_0_0/uub_proto2_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_axi_uartlite_0_0 || ORIG_REF_NAME==uub_proto2_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_0/uub_proto2_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_1_0/uub_proto2_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_2_0/uub_proto2_blk_mem_gen_2_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_3_0/uub_proto2_blk_mem_gen_3_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_4_0/uub_proto2_blk_mem_gen_4_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_6_0/uub_proto2_blk_mem_gen_6_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_proc_sys_reset_0_0/uub_proto2_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_proc_sys_reset_0_0 || ORIG_REF_NAME==uub_proto2_proc_sys_reset_0_0}]

# XDC: bd/uub_proto2/ip/uub_proto2_proc_sys_reset_0_0/uub_proto2_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uub_proto2_proc_sys_reset_0_0 || ORIG_REF_NAME==uub_proto2_proc_sys_reset_0_0}]

# XDC: bd/uub_proto2/ip/uub_proto2_proc_sys_reset_0_0/uub_proto2_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_processing_system7_0_0/uub_proto2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_processing_system7_0_0 || ORIG_REF_NAME==uub_proto2_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_axi_cdma_0_0/uub_proto2_axi_cdma_0_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_cdma_0_0/uub_proto2_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_axi_cdma_0_0 || ORIG_REF_NAME==uub_proto2_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uub_proto2/ip/uub_proto2_xbar_0/uub_proto2_xbar_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_3_1/uub_proto2_blk_mem_gen_3_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_0/uub_proto2_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_1_0/uub_proto2_axi_bram_ctrl_1_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_2_0/uub_proto2_axi_bram_ctrl_2_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_3_0/uub_proto2_axi_bram_ctrl_3_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_4_0/uub_proto2_axi_bram_ctrl_4_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_5_0/uub_proto2_axi_bram_ctrl_5_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_6_0/uub_proto2_axi_bram_ctrl_6_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_fir_compiler_0_1/uub_proto2_fir_compiler_0_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_fir_compiler_0_2/uub_proto2_fir_compiler_0_2_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_fir_compiler_0_3/uub_proto2_fir_compiler_0_3_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_xbar_2/uub_proto2_xbar_2_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_crossbar_0_1/uub_proto2_axi_crossbar_0_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_crossbar_0_0/uub_proto2_axi_crossbar_0_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_crossbar_1_0/uub_proto2_axi_crossbar_1_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_crossbar_2_0/uub_proto2_axi_crossbar_2_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_crossbar_3_0/uub_proto2_axi_crossbar_3_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_crossbar_0_2/uub_proto2_axi_crossbar_0_2_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_crossbar_1_1/uub_proto2_axi_crossbar_1_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_1/uub_proto2_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_2/uub_proto2_blk_mem_gen_0_2_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_3/uub_proto2_blk_mem_gen_0_3_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_4/uub_proto2_blk_mem_gen_0_4_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_blk_mem_gen_0_5/uub_proto2_blk_mem_gen_0_5_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_1/uub_proto2_axi_bram_ctrl_0_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_2/uub_proto2_axi_bram_ctrl_0_2_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_3/uub_proto2_axi_bram_ctrl_0_3_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_4/uub_proto2_axi_bram_ctrl_0_4_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_bram_ctrl_0_5/uub_proto2_axi_bram_ctrl_0_5_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_gpio_0_0/uub_proto2_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_axi_gpio_0_0 || ORIG_REF_NAME==uub_proto2_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uub_proto2/ip/uub_proto2_axi_gpio_0_0/uub_proto2_axi_gpio_0_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_gpio_0_0/uub_proto2_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_axi_gpio_0_0 || ORIG_REF_NAME==uub_proto2_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uub_proto2/ip/uub_proto2_axi_gpio_1_0/uub_proto2_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_axi_gpio_1_0 || ORIG_REF_NAME==uub_proto2_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/uub_proto2/ip/uub_proto2_axi_gpio_1_0/uub_proto2_axi_gpio_1_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_axi_gpio_1_0/uub_proto2_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_axi_gpio_1_0 || ORIG_REF_NAME==uub_proto2_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/uub_proto2/ip/uub_proto2_tier2_xbar_0_0/uub_proto2_tier2_xbar_0_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_tier2_xbar_1_0/uub_proto2_tier2_xbar_1_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_tier2_xbar_2_0/uub_proto2_tier2_xbar_2_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_0/uub_proto2_auto_ds_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_0/uub_proto2_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_0 || ORIG_REF_NAME==uub_proto2_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_1/uub_proto2_auto_ds_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_1/uub_proto2_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_1 || ORIG_REF_NAME==uub_proto2_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_2/uub_proto2_auto_ds_2_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_2/uub_proto2_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_2 || ORIG_REF_NAME==uub_proto2_auto_ds_2}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_3/uub_proto2_auto_ds_3_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_3/uub_proto2_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_3 || ORIG_REF_NAME==uub_proto2_auto_ds_3}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_4/uub_proto2_auto_ds_4_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_4/uub_proto2_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_4 || ORIG_REF_NAME==uub_proto2_auto_ds_4}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_5/uub_proto2_auto_ds_5_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_5/uub_proto2_auto_ds_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_5 || ORIG_REF_NAME==uub_proto2_auto_ds_5}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_6/uub_proto2_auto_ds_6_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_6/uub_proto2_auto_ds_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_6 || ORIG_REF_NAME==uub_proto2_auto_ds_6}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_0/uub_proto2_auto_pc_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_us_0/uub_proto2_auto_us_0_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_us_0/uub_proto2_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_us_0 || ORIG_REF_NAME==uub_proto2_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_us_1/uub_proto2_auto_us_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_us_1/uub_proto2_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_us_1 || ORIG_REF_NAME==uub_proto2_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_7/uub_proto2_auto_ds_7_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_7/uub_proto2_auto_ds_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_7 || ORIG_REF_NAME==uub_proto2_auto_ds_7}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_1/uub_proto2_auto_pc_1_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_8/uub_proto2_auto_ds_8_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_8/uub_proto2_auto_ds_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_8 || ORIG_REF_NAME==uub_proto2_auto_ds_8}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_2/uub_proto2_auto_pc_2_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_9/uub_proto2_auto_ds_9_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_9/uub_proto2_auto_ds_9_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_9 || ORIG_REF_NAME==uub_proto2_auto_ds_9}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_3/uub_proto2_auto_pc_3_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_10/uub_proto2_auto_ds_10_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_10/uub_proto2_auto_ds_10_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_10 || ORIG_REF_NAME==uub_proto2_auto_ds_10}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_4/uub_proto2_auto_pc_4_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_11/uub_proto2_auto_ds_11_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_11/uub_proto2_auto_ds_11_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_11 || ORIG_REF_NAME==uub_proto2_auto_ds_11}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_5/uub_proto2_auto_pc_5_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_12/uub_proto2_auto_ds_12_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_12/uub_proto2_auto_ds_12_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_12 || ORIG_REF_NAME==uub_proto2_auto_ds_12}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_6/uub_proto2_auto_pc_6_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_13/uub_proto2_auto_ds_13_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_13/uub_proto2_auto_ds_13_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_13 || ORIG_REF_NAME==uub_proto2_auto_ds_13}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_14/uub_proto2_auto_ds_14_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_14/uub_proto2_auto_ds_14_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_14 || ORIG_REF_NAME==uub_proto2_auto_ds_14}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_15/uub_proto2_auto_ds_15_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_15/uub_proto2_auto_ds_15_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_15 || ORIG_REF_NAME==uub_proto2_auto_ds_15}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_16/uub_proto2_auto_ds_16_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_16/uub_proto2_auto_ds_16_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_16 || ORIG_REF_NAME==uub_proto2_auto_ds_16}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_17/uub_proto2_auto_ds_17_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_17/uub_proto2_auto_ds_17_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_17 || ORIG_REF_NAME==uub_proto2_auto_ds_17}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_18/uub_proto2_auto_ds_18_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_18/uub_proto2_auto_ds_18_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_18 || ORIG_REF_NAME==uub_proto2_auto_ds_18}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_19/uub_proto2_auto_ds_19_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_19/uub_proto2_auto_ds_19_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_19 || ORIG_REF_NAME==uub_proto2_auto_ds_19}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_20/uub_proto2_auto_ds_20_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_20/uub_proto2_auto_ds_20_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_20 || ORIG_REF_NAME==uub_proto2_auto_ds_20}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_21/uub_proto2_auto_ds_21_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_21/uub_proto2_auto_ds_21_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_21 || ORIG_REF_NAME==uub_proto2_auto_ds_21}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_22/uub_proto2_auto_ds_22_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_22/uub_proto2_auto_ds_22_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_22 || ORIG_REF_NAME==uub_proto2_auto_ds_22}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_23/uub_proto2_auto_ds_23_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_23/uub_proto2_auto_ds_23_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_23 || ORIG_REF_NAME==uub_proto2_auto_ds_23}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_24/uub_proto2_auto_ds_24_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_24/uub_proto2_auto_ds_24_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_24 || ORIG_REF_NAME==uub_proto2_auto_ds_24}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_25/uub_proto2_auto_ds_25_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_25/uub_proto2_auto_ds_25_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_25 || ORIG_REF_NAME==uub_proto2_auto_ds_25}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_7/uub_proto2_auto_pc_7_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_26/uub_proto2_auto_ds_26_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_ds_26/uub_proto2_auto_ds_26_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_ds_26 || ORIG_REF_NAME==uub_proto2_auto_ds_26}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_8/uub_proto2_auto_pc_8_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_pc_9/uub_proto2_auto_pc_9_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_us_2/uub_proto2_auto_us_2_ooc.xdc

# XDC: bd/uub_proto2/ip/uub_proto2_auto_us_2/uub_proto2_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uub_proto2_auto_us_2 || ORIG_REF_NAME==uub_proto2_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/uub_proto2/uub_proto2_ooc.xdc
