webtalk_init -webtalk_dir C:\\Xilinx\\Vivado\\2015.2\\progetti\\uub_nitz_assiro\\uub_proto2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "mer nov 9 19:30:29 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "64qcoqocfd4es1l2ugdoslrvp2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1478524348651" -context "sdk\\\\application/1478524348651"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1478524348651"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1478524348651"
webtalk_add_data -client sdk -key uid -value "1478684885798" -context "sdk\\\\application/1478684885798"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1478684885798"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1478684885798"
webtalk_transmit -clientid 2465334271 -regid "" -xml C:\\Xilinx\\Vivado\\2015.2\\progetti\\uub_nitz_assiro\\uub_proto2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Xilinx\\Vivado\\2015.2\\progetti\\uub_nitz_assiro\\uub_proto2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Xilinx\\Vivado\\2015.2\\progetti\\uub_nitz_assiro\\uub_proto2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
