# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/xilinx/vivado/2015.2/progetti/uub_nitz_assiro_new/uub_proto2.tmp/delay_input_v1_1_project/delay_input_v1_1_project.cache/wt [current_project]
set_property parent.project_path c:/xilinx/vivado/2015.2/progetti/uub_nitz_assiro_new/uub_proto2.tmp/delay_input_v1_1_project/delay_input_v1_1_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Xilinx/Vivado/2015.2/progetti/uub_nitz_assiro_new/ip_repo [current_project]
read_vhdl -library xil_defaultlib c:/xilinx/vivado/2015.2/progetti/uub_nitz_assiro_new/ip_repo/delay_input/delay_input.vhd
synth_design -top delay_input -part xc7z020clg484-1
write_checkpoint -noxdef delay_input.dcp
catch { report_utilization -file delay_input_utilization_synth.rpt -pb delay_input_utilization_synth.pb }
